# Generated by Django 3.2.9 on 2021-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('user', models.CharField(max_length=90, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('password', models.CharField(max_length=80, null=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
